// pkg/models/action_collector.go
package models

// ActionCollector collects actions generated by rules
type ActionCollector struct {
    actions []Action
}

// NewActionCollector creates a new action collector
func NewActionCollector() *ActionCollector {
    return &ActionCollector{
        actions: make([]Action, 0),
    }
}

// AddSpawnAction adds a spawn action
func (ac *ActionCollector) AddSpawnAction(actionType, zone, unitType, count string) {
    action := Action{
        Type:     "spawn",
        SubType:  actionType,
        Zone:     zone,
        UnitType: unitType,
        Count:    count,
    }
    ac.actions = append(ac.actions, action)
}

// AddAlertAction adds an alert action
func (ac *ActionCollector) AddAlertAction(actionType, level, message string) {
    action := Action{
        Type:    "alert",
        SubType: actionType,
        Level:   level,
        Message: message,
    }
    ac.actions = append(ac.actions, action)
}

// GetActions returns all collected actions
func (ac *ActionCollector) GetActions() []Action {
    return ac.actions
}
